console.log("🚨 SERVER STARTED — gemini-2.5-flash ONLY");

import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import fetch from "node-fetch";

dotenv.config();

const app = express();
const PORT = process.env.PORT || 5000;

// ===================== MIDDLEWARE =====================
app.use(cors());
app.use(express.json());

// ===================== ENV CHECK =====================
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;

if (!GEMINI_API_KEY) {
  console.error("❌ GEMINI_API_KEY is missing in .env file");
  process.exit(1);
}

// ===================== MODEL CONFIG =====================
const MODEL = "gemini-2.5-flash"; // supported by your API key

const GEMINI_URL =
  `https://generativelanguage.googleapis.com/v1/models/${MODEL}:generateContent?key=${GEMINI_API_KEY}`;
console.log("🤖 GEMINI URL =", GEMINI_URL);

// ===================== ROUTES =====================

// Health check
app.get("/", (req, res) => {
  res.json({
    status: "Backend running 🚀",
    model: MODEL
  });
});

// Main AI endpoint
app.post("/api/ask", async (req, res) => {
  const { question } = req.body;

  if (!question || typeof question !== "string") {
    return res.status(400).json({
      error: "Question must be a non-empty string"
    });
  }

  const requestBody = {
    contents: [
      {
        role: "user",
        parts: [
          {
            text: `
You are a strict coding instructor.

Rules:
- Answer ONLY coding-related questions.
- If the question is NOT about coding, respond rudely.
- If it IS about coding, explain clearly with examples if needed.

Question:
${question}
            `.trim()
          }
        ]
      }
    ]
  };

  try {
    const response = await fetch(GEMINI_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify(requestBody)
    });

    const data = await response.json();

    if (!response.ok) {
      console.error("❌ Gemini API Error:", data);
      return res.status(500).json({
        error: data.error?.message || "Gemini API failed"
      });
    }

    const answer =
      data?.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!answer) {
      return res.status(500).json({
        error: "No response generated by Gemini"
      });
    }

    res.json({ answer });

  } catch (err) {
    console.error("❌ Server Error:", err);
    res.status(500).json({
      error: "Internal server error"
    });
  }
});

// ===================== START SERVER =====================
app.listen(PORT, () => {
  console.log(`✅ Server running on http://localhost:${PORT}`);
  console.log(`🤖 Using model: ${MODEL}`);
});
